---
title: "Simple document"
output:  github_document

---
```{r setup, include = FALSE}
library(tidyverse)
```
#Question 1
```{r}
data("penguins", package = "palmerpenguins")
```
The variables of the dataset are `r colnames(penguins)`. 
The dataset has `r ncol(penguins)` columns and `r nrow(penguins)` rows. 
The mean flipper length is `r mean(pull(penguins, flipper_length_mm), na.rm = TRUE)`.  

```{r}
scatterplot <- ggplot(data = penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()

print(scatterplot)

ggsave("hw1_scatterplot.png", plot = scatterplot)
```

#Question 2
```{r}
library(tidyverse)
hw1_df = tibble(
  norm_samp = rnorm(10, mean = 1),
  norm_samp_pos = norm_samp > 0,
  vec_char =c("im", "not", "sure", "if", "im", "doing", "this",
              "correctly","oh", "well"),
  vec_factor = factor(c("low", "medium", "high", "low", "high", 
                          "medium", "low", "high", "medium", "low"))
)

mean(pull(hw1_df, vec_char))

mean(pull(hw1_df,vec_factor))

mean(pull(hw1_df, norm_samp))

mean(pull(hw1_df, norm_samp_pos))
```
When taking the mean of each variable in the dataframe, I realized that I could only take the mean of the numeric variables. 



